### GET
GET http://localhost:3000/api/recept HTTP/1.1

### GET
GET http://localhost:3000/api/recept/sorted?id=4 HTTP/1.1

### GET
GET http://localhost:3000/api/recept/sorted?shop=cssfc HTTP/1.1

### GET
GET http://localhost:3000/api/recept/sorted?category=testi HTTP/1.1

### GET
GET http://localhost:3000/api/recept/sorted?date=2022-01-14 HTTP/1.1

### GET
GET http://localhost:3000/api/recept/month/January HTTP/1.1

### GET
GET http://localhost:3000/api/recept/order/testi HTTP/1.1

###
POST http://localhost:3000/api/recept/
Content-Type: application/json

{
    "date": "2023-01-01",
    "amount": 100.0,
    "shop": "cssfc",
    "category": "fvvs"
}

###
PUT http://localhost:3000/api/recept/2
Content-Type: application/json

{
    "date": "2021-01-01",
    "amount": 100,
    "shop": "ICA",
    "category": "Mat"
}

###
DELETE http://localhost:3000/api/recept/2 HTTP/1.1